name: Flutter Web Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # pubspecのSDKバージョンに合わせる場合はここで指定（例: flutter-version: '3.19.0'）

      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Build Web
        working-directory: ./app
        run: flutter build web --base-href "/to-do-rock/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web
